# Generated by Django 5.0.3 on 2024-03-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_request_requested_blood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requested_blood',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
