# Generated by Django 5.0.3 on 2024-03-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_request_requested_blood'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='recipient_state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
