# Generated by Django 5.0.3 on 2024-03-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_request_recipient_state_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
