# file created: 2024-03-17 03:53:42.944675

# this files has been generated by CandyTranslate.com  Please do not change manually
# author: Next Level Sense

# Available functions:
#    render - replacement for django render function
#    path - replacement for django path function. please use with * when replacing in urls.py
#    supported_languages - list that contains all available languages for this site
# Functions to be used in django templates:
#    languageReferences - create 'alternate' language references for SEO.
#        put it inside of the <head> section of the page in format {{languageReferences|safe}}
#    lang - current language. Used mostly in <html lang="{{lang}}">
#    languageMenu - adding language selection for your page. Format: {{languageMenu|safe}}
#    <<link variables>> - create linking to correct language link. 
#    usage:
#    for translated pages change {% url "my_page" %}
#    to name without quotes:     {% url my_page %}


supported_languages = ['en', 'bn', 'hi', 'pa', 'ta', 'ur']

def translation_dictionary(lang):
    if lang == 'en': return {
        'home_welcome':'''Welcome,''',
        'home_logout':'''Logout''',
        'home_login':'''Login''',
        'home_register':'''Register''',
        'home_empowering':'''Empowering Humanity through Compassion''',
        'home_revolutionizing':'''Revolutionizing Blood Donation for a Healthier Tomorrow!''',
        'home_donate_now':'''DONATE NOW''',
        'home_find_a_donorr':'''FIND A DONOR''',
        'home_why_donation_crucial':'''Why Blood Donation is Crucial?''',
        'home_donation_cruicial_explain':'''Blood donation is a selfless act that holds the power ​to save lives and contribute to the well-being of ​communities. The importance of blood donation lies ​in its ability to provide a lifeline to individuals facing ​medical emergencies, surgeries, accidents, and ​chronic illnesses. It is a fundamental cornerstone of ​healthcare systems globally, ensuring the availability ​of safe and vital blood units for those in need.''',
        'home_our_services':'''Our Services''',
        'home_find_a_donor':'''Find''',
        'home_find_volunteer_donors':'''Find volunteer donors''',
        'home_who_are_ready':'''who are ready to''',
        'home_donate_through':'''donate through our''',
        'home_application_directly':'''application directly''',
        'home_connect':'''Connect''',
        'home_contact_donors':'''contact donors directly''',
        'home_through_the':'''through the''',
        'home_app_without':'''application without''',
        'home_intermediaries':'''intermediaries''',
        'home_donate':'''Donate''',
        'home_donate_blood':'''Donate blood''',
        'home_according_to_the':'''according to the''',
        'home_location_of_need':'''location of need''',
        'home_steps_to_donate':'''Steps to Donate''',
        'home_register_healthProfile':'''Register and Complete your Health Profile''',
        'home_create_crimsonConnect':'''Create your CrimsonConnect account to become part of our community. Fill in essential health information to ensure a safe and efficient donation process.''',
        'home_find_nearby':'''Find nearby Recipients and Donation Drives''',
        'home_locate_join':'''Locate and join urgent needs and blood donation drives in your vicinity through our user-friendly interface.''',
        'home_connect_recipients':'''Connect with Recipients''',
        'home_chat_with_recipients':'''Chat with recipients and blood banks in real-time. Confirm appointment details, address any concerns, and ensure a smooth process for everyone involved.''',
        'home_client_testimonials':'''Client Testimonials''',
        'home_we_value':'''We value''',
        'home_your_feedback':'''your feedback''',
        'home_joining_blood_donation':'''Joining the blood donation network was one of the best decisions I've made. The process was seamless, and I found comfort knowing my profile was complete, ensuring a swift response when my blood was needed.''',
        'home_sharman_grover':'''- Sharman Grover''',
        'home_completing_my_health':'''Completing my health profile was quick and easy, and being part of the blood donation network gives me a sense of purpose. Knowing that my information is readily available to help someone in need is incredibly rewarding''',
        'home_natasha_lamba':'''- Natasha Lamba''',
        'home_registering_blood_donation':'''Registering for the blood donation network was a breeze. The platform made it simple to update my health profile, ensuring accurate information for potential donations. It's fulfilling to know I'm making a difference in someone's life.''',
        'home_jayant_daya':'''- Jayant Daya''',
        }
    if lang == 'bn': return {
        'home_welcome':'''স্বাগত''',
        'home_logout':'''প্রস্থান''',
        'home_login':'''প্রবেশ করুন''',
        'home_register':'''নিবন্ধন''',
        'home_empowering':'''ক্ষমতায়ন''',
        'home_revolutionizing':'''বিপ্লব''',
        'home_donate_now':'''এখনি দান করো''',
        'home_find_a_donorr':'''Find_a_donorr''',
        'home_why_donation_crucial':'''কেন_ডোনেশন_ক্রুসিয়াল''',
        'home_donation_cruicial_explain':'''অনুদান_ক্রুইশিয়াল_এক্সপ্লেইন''',
        'home_our_services':'''আমাদের সেবাসমূহ''',
        'home_find_a_donor':'''Find_A_DONOR''',
        'home_find_volunteer_donors':'''Find_volunteer_doners''',
        'home_who_are_ready':'''WHO_ARE_READY''',
        'home_donate_through':'''দান_আউট্রু''',
        'home_application_directly':'''অ্যাপ্লিকেশন_ডাইরেক্টলি''',
        'home_connect':'''সংযুক্ত''',
        'home_contact_donors':'''যোগাযোগ_ডোনার্স''',
        'home_through_the':'''মাধ্যমে_''',
        'home_app_without':'''app_without''',
        'home_intermediaries':'''মধ্যস্থতাকারী''',
        'home_donate':'''দান করুন''',
        'home_donate_blood':'''রক্ত দান''',
        'home_according_to_the':'''অনুযায়ী''',
        'home_location_of_need':'''অবস্থান_অফ_নিড''',
        'home_steps_to_donate':'''steps_to_donate''',
        'home_register_healthProfile':'''নিবন্ধন_হেলথপ্রোফাইল''',
        'home_create_crimsonConnect':'''create_crimsonconnect''',
        'home_find_nearby':'''Find_nearby''',
        'home_locate_join':'''লোকেট_জাইন''',
        'home_connect_recipients':'''সংযোগ_রিসিপিয়েন্টস''',
        'home_chat_with_recipients':'''CHAT_WITH_RECIPIents''',
        'home_client_testimonials':'''ক্লায়েন্ট_ টেস্টিমোনিয়ালস''',
        'home_we_value':'''আমরা মূল্য দেই''',
        'home_your_feedback':'''আপনার_ফিডব্যাক''',
        'home_joining_blood_donation':'''যোগদান_ব্লুড_ডোনেশন''',
        'home_sharman_grover':'''শারম্যান_গ্রোভার''',
        'home_completing_my_health':'''সম্পূর্ণ করা_মাই_হেলথ''',
        'home_natasha_lamba':'''নাতাশা_লম্বা''',
        'home_registering_blood_donation':'''নিবন্ধকরণ_ব্লুড_ডোনেশন''',
        'home_jayant_daya':'''জয়ন্ত_ডিয়া''',
        }
    if lang == 'hi': return {
        'home_welcome':'''स्वागत''',
        'home_logout':'''लॉग आउट''',
        'home_login':'''लॉग इन करें''',
        'home_register':'''पंजीकरण करवाना''',
        'home_empowering':'''सशक्त बनाने''',
        'home_revolutionizing':'''क्रांति''',
        'home_donate_now':'''अभी दान कीजिए''',
        'home_find_a_donorr':'''find_a_donorr''',
        'home_why_donation_crucial':'''Why_donation_crucial''',
        'home_donation_cruicial_explain':'''doination_cruicial_explain''',
        'home_our_services':'''हमारी सेवाएँ''',
        'home_find_a_donor':'''find_a_donor''',
        'home_find_volunteer_donors':'''find_volunteer_donors''',
        'home_who_are_ready':'''who_are_ready''',
        'home_donate_through':'''donate_through''',
        'home_application_directly':'''application_directly''',
        'home_connect':'''जोड़ना''',
        'home_contact_donors':'''contact_donors''',
        'home_through_the':'''के माध्यम से''',
        'home_app_without':'''app_without''',
        'home_intermediaries':'''बिचौलियों''',
        'home_donate':'''दान करें''',
        'home_donate_blood':'''रक्त दान करें''',
        'home_according_to_the':'''के अनुसार''',
        'home_location_of_need':'''स्थान_ोफ़_नेड''',
        'home_steps_to_donate':'''step_to_donate''',
        'home_register_healthProfile':'''रजिस्टर_हेल्थप्रोफाइल''',
        'home_create_crimsonConnect':'''create_crimsonconnect''',
        'home_find_nearby':'''find_nearby''',
        'home_locate_join':'''locate_join''',
        'home_connect_recipients':'''कनेक्ट_रेसिपिएंट्स''',
        'home_chat_with_recipients':'''chat_with_recipients''',
        'home_client_testimonials':'''ग्राहकों की गवाही''',
        'home_we_value':'''हम आदर देते है''',
        'home_your_feedback':'''आपकी प्रतिक्रिया''',
        'home_joining_blood_donation':'''JOINING_BLOOD_DONATION''',
        'home_sharman_grover':'''SHARMAN_GROVER''',
        'home_completing_my_health':'''पूरा करना_my_health''',
        'home_natasha_lamba':'''नताशा_लाम्बा''',
        'home_registering_blood_donation':'''रजिस्टर_ब्लड_डोनेशन''',
        'home_jayant_daya':'''jayant_daya''',
        }
    if lang == 'pa': return {
        'home_welcome':'''ਜੀ ਆਇਆਂ ਨੂੰ''',
        'home_logout':'''ਲਾੱਗ ਆਊਟ, ਬਾਹਰ ਆਉਣਾ''',
        'home_login':'''ਲਾਗਿਨ''',
        'home_register':'''ਰਜਿਸਟਰ''',
        'home_empowering':'''ਸ਼ਕਤੀਕਰਨ''',
        'home_revolutionizing':'''ਇਨਕਲਾਤੀ''',
        'home_donate_now':'''ਡੋਨਟ_ਵਨੋ''',
        'home_find_a_donorr':'''ਲੱਭੋ_ਏ_ਡੋਨੋਰਰ''',
        'home_why_donation_crucial':'''ਕਿਉਂ_ਡੋਨੇਸ਼ਨ_ਕ੍ਰਿਤੀ''',
        'home_donation_cruicial_explain':'''ਦਾਨ_ਕ੍ਰਾਈਅਲ_ ਐਕਸਪੋਲਿਨ''',
        'home_our_services':'''ਸਾਡੀ ਸੇਵਾਵਾਂ''',
        'home_find_a_donor':'''ਲੱਭੋ''',
        'home_find_volunteer_donors':'''ਲੱਭੋ_ਵੋਲਟੀਅਰ_ਡੋਨੋਰਸ''',
        'home_who_are_ready':'''ਕੌਣ_ਰੇ_ ਤਿਆਰ''',
        'home_donate_through':'''ਦਾਨ_ਥਰੂ''',
        'home_application_directly':'''ਐਪਲੀਕੇਸ਼ਨ_-ਡਾਇਰੈਕਟਿਵ''',
        'home_connect':'''ਕਨੈਕਟ ਕਰੋ''',
        'home_contact_donors':'''ਸੰਪਰਕ_ਡੋਨੋਰਸ''',
        'home_through_the':'''ਦੁਆਰਾ''',
        'home_app_without':'''ਐਪ_ਵਿਥ''',
        'home_intermediaries':'''ਵਿਚੋਲਗੀ''',
        'home_donate':'''ਦਾਨ''',
        'home_donate_blood':'''ਡੋਨਟ_ਬਾਇਲ''',
        'home_according_to_the':'''ਇਸਦੇ ਅਨੁਸਾਰ''',
        'home_location_of_need':'''ਟਿਕਾਣਾ_ਫ_ਨਿਡ''',
        'home_steps_to_donate':'''ਸਟੈਪਸ_ਟੋ_ਡੋਨੇਟ''',
        'home_register_healthProfile':'''ਰਜਿਸਟਰ_ਹੈਲਫੋਫਾਈਲ''',
        'home_create_crimsonConnect':'''ਬਣਾਓ_ ਕ੍ਰਿਮਸਨ ਕਨੈਕਟ''',
        'home_find_nearby':'''ਲੱਭੋ_ਨੇਅਰਬੀ''',
        'home_locate_join':'''ਲੱਭੋ_ਜੋਇਨ''',
        'home_connect_recipients':'''ਕਨੈਕਟ_ਰੇਸੀਓਂਟ''',
        'home_chat_with_recipients':'''ਚੈਟ_ਵਿਥ_ਆਰਕੋਇੰਟਸ''',
        'home_client_testimonials':'''ਕਲਾਇੰਟ_ਸਟਿਮੋਨਿਅਲਜ਼''',
        'home_we_value':'''We_Value''',
        'home_your_feedback':'''ਤੁਹਾਡਾ_ਕੱਪਬੈਕ''',
        'home_joining_blood_donation':'''ਸ਼ਾਮਲ ਹੋ ਰਹੇ_ਬੁੱਲ_ਡੋਨੇਸ਼ਨ''',
        'home_sharman_grover':'''ਸ਼ਾਰਮੈਨ_ਗ੍ਰੋਵਰ''',
        'home_completing_my_health':'''ਪੂਰਾ ਕਰ ਰਿਹਾ ਹੈ_ਮੀਲਥ''',
        'home_natasha_lamba':'''Natash_lamba''',
        'home_registering_blood_donation':'''ਰਜਿਸਟਰ_ਬੁੱਲ_ਡੋਨੇਸ਼ਨ''',
        'home_jayant_daya':'''ਜੈੰਤ ਡੀਡੇਆ''',
        }
    if lang == 'ta': return {
        'home_welcome':'''வரவேற்பு''',
        'home_logout':'''வெளியேறு''',
        'home_login':'''உள்நுழைய''',
        'home_register':'''பதிவு''',
        'home_empowering':'''அதிகாரம்''',
        'home_revolutionizing':'''புரட்சி''',
        'home_donate_now':'''நன்கொடை_நவ்''',
        'home_find_a_donorr':'''find_a_donorr''',
        'home_why_donation_crucial':'''why_donation_crousial''',
        'home_donation_cruicial_explain':'''நன்கொடை_ க்ரூயல்_எக்ஸ்ப்ளேன்''',
        'home_our_services':'''எங்கள்_ சேவைகள்''',
        'home_find_a_donor':'''find_a_donor''',
        'home_find_volunteer_donors':'''find_volunteer_donors''',
        'home_who_are_ready':'''WHO_ARE_READY''',
        'home_donate_through':'''நன்கொடை''',
        'home_application_directly':'''application_directly''',
        'home_connect':'''இணைக்கவும்''',
        'home_contact_donors':'''CONCATION_DONORS''',
        'home_through_the':'''மூலம்_தே''',
        'home_app_without':'''app_whithout''',
        'home_intermediaries':'''இடைத்தரகர்கள்''',
        'home_donate':'''நன்கொடை''',
        'home_donate_blood':'''நன்கொடை_ ப்ளூட்''',
        'home_according_to_the':'''அதில் கூறியபடி''',
        'home_location_of_need':'''Location_of_need''',
        'home_steps_to_donate':'''Steps_to_donate''',
        'home_register_healthProfile':'''register_healthprofile''',
        'home_create_crimsonConnect':'''create_crimsonconnect''',
        'home_find_nearby':'''find_nearby''',
        'home_locate_join':'''locate_join''',
        'home_connect_recipients':'''connect_recipients''',
        'home_chat_with_recipients':'''Chat_with_recipients''',
        'home_client_testimonials':'''client_testimonials''',
        'home_we_value':'''we_value''',
        'home_your_feedback':'''உங்கள்_ஃபீட்பேக்''',
        'home_joining_blood_donation':'''சேரும்_பிலூட்_டோனேஷன்''',
        'home_sharman_grover':'''sharman_grover''',
        'home_completing_my_health':'''முடித்தல்_மீ_ஹெல்த்''',
        'home_natasha_lamba':'''நடாஷா_ லாம்பா''',
        'home_registering_blood_donation':'''பதிவுசெய்தல்_பிலூட்_டோனேஷன்''',
        'home_jayant_daya':'''ஜெயந்த்_ய்தா''',
        }
    if lang == 'ur': return {
        'home_welcome':'''خوش آمدید''',
        'home_logout':'''لاگ آوٹ''',
        'home_login':'''لاگ ان کریں''',
        'home_register':'''اندراج کریں''',
        'home_empowering':'''بااختیار بنانا''',
        'home_revolutionizing':'''انقلاب لانا''',
        'home_donate_now':'''ابھی عطیہ کیجیے''',
        'home_find_a_donorr':'''find_a_donorr''',
        'home_why_donation_crucial':'''کیوں_ڈونشن_کریوئیل''',
        'home_donation_cruicial_explain':'''عطیہ_کریوئل_کسپلین''',
        'home_our_services':'''ہماری خدمات''',
        'home_find_a_donor':'''find_a_donor''',
        'home_find_volunteer_donors':'''find_volunteer_donors''',
        'home_who_are_ready':'''WHO_ARE_READY''',
        'home_donate_through':'''ڈونیٹ_تھرو''',
        'home_application_directly':'''درخواست_ ڈائریکٹ''',
        'home_connect':'''جڑیں''',
        'home_contact_donors':'''رابطہ_ڈونرز''',
        'home_through_the':'''کے ذریعے''',
        'home_app_without':'''app_without آؤٹ''',
        'home_intermediaries':'''بیچوان''',
        'home_donate':'''عطیہ کریں''',
        'home_donate_blood':'''ڈونیٹ_ بلڈ''',
        'home_according_to_the':'''کے مطابق''',
        'home_location_of_need':'''location_of_need''',
        'home_steps_to_donate':'''steps_to_donate''',
        'home_register_healthProfile':'''رجسٹر_ ہیلتھ پروفائل''',
        'home_create_crimsonConnect':'''create_crimsonconnect''',
        'home_find_nearby':'''find_nearby''',
        'home_locate_join':'''لوکیٹ_جون''',
        'home_connect_recipients':'''Connect_recipients''',
        'home_chat_with_recipients':'''chat_with_recipients''',
        'home_client_testimonials':'''کلائنٹ_ٹیسٹیمونیلز''',
        'home_we_value':'''ہم_ایلیو''',
        'home_your_feedback':'''آپ کی رائے''',
        'home_joining_blood_donation':'''شامل ہونا_ بلڈ_ڈونشن''',
        'home_sharman_grover':'''شرمن_گروور''',
        'home_completing_my_health':'''مکمل_یمی_ ہیلتھ''',
        'home_natasha_lamba':'''نتاشا_لامبا''',
        'home_registering_blood_donation':'''رجسٹرنگ_ بلڈ_ڈیشن''',
        'home_jayant_daya':'''jaanant_daya''',
        }


def detectLanguage(request):
    languageDetected = supported_languages[0]
    pagePath = request.path
    if pagePath[-1] == '/': pagePath=pagePath[:-1]
    pagePath = pagePath.split('?')[0]
    pagePath = pagePath.split('#')[0]
    lastPath = pagePath.split('/')[-1]
    if lastPath in supported_languages[1:]:
        languageDetected = lastPath
    return languageDetected


def translated(requestOrLang,TranslateVariable):
    if requestOrLang in supported_languages:
        lang=requestOrLang
    else:
        lang = detectLanguage(requestOrLang)
    return translation_dictionary(lang)[TranslateVariable]


def localizeLink(request, link):
    lang=detectLanguage(request)
    if lang == supported_languages[0]: return link
    index1 = link.find('#')
    index2 = link.find('?')
    if index1 == -1 and index2 == -1: smallest_index = len(link)
    elif index1 == -1: smallest_index = index2
    elif index2 == -1: smallest_index = index1
    else: smallest_index = min(index1, index2)
    path = link[:smallest_index]
    if path[-1] == '/': path=path[:-1]
    return path+'/'+lang+link[smallest_index:]


from django.shortcuts import redirect as org_redirect
def redirect(request, to, *args, permanent=False, **kwargs):
    lang=detectLanguage(request)
    if lang in supported_languages[1:]:
        to=to+'_'+lang
    return org_redirect(to, *args, permanent=permanent, **kwargs)


from django.urls import path as org_path
def path(route, view, kwargs=None, name=None):
    if route == '':
        return [org_path('', view, kwargs, name),org_path('bn', view, kwargs, name+'_bn'),org_path('hi', view, kwargs, name+'_hi'),org_path('pa', view, kwargs, name+'_pa'),org_path('ta', view, kwargs, name+'_ta'),org_path('ur', view, kwargs, name+'_ur'),]
    if route[-1] == '/': route=route[:-1]
    return [org_path(route, view, kwargs, name),org_path(route+'/bn', view, kwargs, name+'_bn'),org_path(route+'/hi', view, kwargs, name+'_hi'),org_path(route+'/pa', view, kwargs, name+'_pa'),org_path(route+'/ta', view, kwargs, name+'_ta'),org_path(route+'/ur', view, kwargs, name+'_ur'),]


def langRef(path_ref):
    last=path_ref.split('/')[-1]
    if last in supported_languages:
        path_ref=path_ref[:-len(last)-1]
    result='<link rel="alternate" hreflang="en" href="'+addLinks(path_ref,'')+'" />\n'
    result+='<link rel="alternate" hreflang="bn" href="'+addLinks(path_ref,'bn')+'" />\n'
    result+='<link rel="alternate" hreflang="hi" href="'+addLinks(path_ref,'hi')+'" />\n'
    result+='<link rel="alternate" hreflang="pa" href="'+addLinks(path_ref,'pa')+'" />\n'
    result+='<link rel="alternate" hreflang="ta" href="'+addLinks(path_ref,'ta')+'" />\n'
    result+='<link rel="alternate" hreflang="ur" href="'+addLinks(path_ref,'ur')+'" />\n'
    result+='<link rel="alternate" hreflang="x-default" href="'+addLinks(path_ref,'')+'" />\n'
    return result


from django.urls import get_resolver
def translatedLinks(lang):
    names=[]
    for i in get_resolver().url_patterns:
        if hasattr(i, 'name'):
            if i.name:
                names.append(i.name)
    result = {}
    if lang == supported_languages[0]:
        for i in names:
            if i[-3:] not in ['_bn', '_hi', '_pa', '_ta', '_ur'] and names.count(i+'_bn'):
                result.update({i:i})
        return result
    for i in names:
        if names.count(i+'_'+lang):
            result.update({i:i+'_'+lang})
    return result


def languageMenu(request, lang):
    path = request.path
    remainder = request.get_full_path()[len(path):]
    selected = [' ', ' ', ' ', ' ', ' ', ' ']
    selected[supported_languages.index(lang)]=' selected '
    if supported_languages.index(lang):
        path=path[:-3]
    result = '<select id="languageMenu" onchange="window.location = this.value;">'
    if path == '/': path = ''
    if path =='':
        result += '<option'+selected[0]+'value="/'+remainder+'">English (English)</option>'
    else:
        result += '<option'+selected[0]+'value="' + path + remainder +'">English (English)</option>'
    result += '<option'+selected[1]+'value="' + path +'/bn'+remainder+'">Bengali (বাংলা)</option>'
    result += '<option'+selected[2]+'value="' + path +'/hi'+remainder+'">Hindi (हिन्दी)</option>'
    result += '<option'+selected[3]+'value="' + path +'/pa'+remainder+'">Punjabi (ਪੰਜਾਬੀ)</option>'
    result += '<option'+selected[4]+'value="' + path +'/ta'+remainder+'">Tamil (தமிழ்)</option>'
    result += '<option'+selected[5]+'value="' + path +'/ur'+remainder+'">Urdu (اردو)</option>'
    result += '</select>'
    return result


from django.shortcuts import render as org_render
def render(request, template_name, context=None, *args, **kwargs):
    lang=detectLanguage(request)
    if context == None:
        context={}
    return org_render(request, template_name, {**context,
                                                **translation_dictionary(lang),
                                                'lang':lang,
                                                'languageReferences':langRef(request.build_absolute_uri()),
                                                'languageMenu':languageMenu(request, lang),
                                                'candyLink':translatedLinks(lang),
                                                }, *args, **kwargs)


def addLinks(*args):
    result=''
    for i in args:
        if result and result[-1]=='/':result=result[:-1]
        if i and i[-1]=='/':i=i[:-1]
        if i and i[0]=='/':i=i[1:]
        if result and i: result+='/'
        result+=i
    return result


def provideSitemap(request, add_pages=[], remove_pages=[], remove_paths=[]):
    from django.http import HttpResponse
    result='<?xml version="1.0" encoding="UTF-8"?>'+'\n'
    result+='<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+'\n'
    domain= request.build_absolute_uri()
    domain=domain.split('/')[0]+'//'+domain.split('/')[2]+'/'
    paths = []
    for i in get_resolver().url_patterns:
        if str(type(i))=="<class 'django.urls.resolvers.URLPattern'>":
            try:
                route=i.pattern._route
                route=route.split('<')[0]
                if not route == 'sitemap.xml':
                    if 'robots.txt' not in route:
                        paths.append(addLinks(domain,route))
            except: pass
    paths+=add_pages
    paths=list(dict.fromkeys(paths))
    for route in paths:
        removed_path = False
        for removal in remove_paths:
            if route[:len(removal)] == removal: removed_path = True
        if not removed_path and route not in remove_pages:
            result+='<url>'+'\n'
            result+='<loc>'+route+'</loc>'+'\n'
            result+='</url>'+'\n'
    result+='</urlset>'
    result= result.encode('utf-8')
    return HttpResponse(result, content_type='application/xml; charset=utf-8')


def sitemap(add_pages=[], remove_pages=[], remove_paths=[]):
    return [org_path('sitemap.xml', provideSitemap,{'add_pages' :add_pages,'remove_pages': remove_pages, 'remove_paths': remove_paths})]


